import type { User, Ticket, Comment, Label } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'user-admin-1',
    email: 'admin@ciclovida.com',
    name: 'Ana Admin',
    role: 'admin',
    active: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-dev-1',
    email: 'carlos@ciclovida.com',
    name: 'Carlos Dev',
    role: 'usuario',
    active: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 'user-dev-2',
    email: 'maria@ciclovida.com',
    name: 'María QA',
    role: 'usuario',
    active: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'user-inactive-1',
    email: 'pedro@ciclovida.com',
    name: 'Pedro Inactivo',
    role: 'usuario',
    active: false,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-06-01T00:00:00Z',
  },
];

export const MOCK_LABELS: Label[] = [
  { id: 'label-1', name: 'bug' },
  { id: 'label-2', name: 'feature' },
  { id: 'label-3', name: 'mejora' },
  { id: 'label-4', name: 'documentación' },
];

export const MOCK_TICKETS: Ticket[] = [
  {
    id: 'ticket-1',
    title: 'Configurar pipeline de CI/CD',
    description: '<p>Configurar GitHub Actions para builds automáticos.</p>',
    status: 'por_hacer',
    priority: 'alta',
    createdBy: MOCK_USERS[0],
    assignedTo: MOCK_USERS[1],
    labels: [MOCK_LABELS[1]],
    archivedAt: null,
    createdAt: '2025-04-01T10:00:00Z',
    updatedAt: '2025-04-01T10:00:00Z',
  },
  {
    id: 'ticket-2',
    title: 'Diseñar pantalla de login',
    description: '<p>Mockups en Figma + implementación React.</p>',
    status: 'en_progreso',
    priority: 'media',
    createdBy: MOCK_USERS[1],
    assignedTo: MOCK_USERS[2],
    labels: [MOCK_LABELS[1], MOCK_LABELS[2]],
    archivedAt: null,
    createdAt: '2025-04-02T09:00:00Z',
    updatedAt: '2025-04-10T14:00:00Z',
  },
  {
    id: 'ticket-3',
    title: 'Corregir error 500 en endpoint /auth/me',
    description: '<p>Se produce cuando la cookie expira sin token de refresco.</p>',
    status: 'review',
    priority: 'alta',
    createdBy: MOCK_USERS[2],
    assignedTo: MOCK_USERS[0],
    labels: [MOCK_LABELS[0]],
    archivedAt: null,
    createdAt: '2025-04-05T08:30:00Z',
    updatedAt: '2025-04-12T11:00:00Z',
  },
  {
    id: 'ticket-4',
    title: 'Actualizar dependencias npm',
    description: null,
    status: 'listo',
    priority: 'baja',
    createdBy: MOCK_USERS[1],
    assignedTo: null,
    labels: [],
    archivedAt: null,
    createdAt: '2025-03-20T12:00:00Z',
    updatedAt: '2025-04-08T16:00:00Z',
  },
  {
    id: 'ticket-5',
    title: 'Integración con proveedor de pagos',
    description: '<p>Bloqueado por falta de credenciales del proveedor.</p>',
    status: 'bloqueado',
    priority: 'alta',
    createdBy: MOCK_USERS[0],
    assignedTo: MOCK_USERS[1],
    labels: [MOCK_LABELS[1]],
    archivedAt: null,
    createdAt: '2025-04-03T15:00:00Z',
    updatedAt: '2025-04-03T15:00:00Z',
  },
  {
    id: 'ticket-6',
    title: 'Escribir tests unitarios para authStore',
    description: '<p>Cubrir casos: login, logout, sesión expirada.</p>',
    status: 'por_hacer',
    priority: 'media',
    createdBy: MOCK_USERS[2],
    assignedTo: MOCK_USERS[2],
    labels: [MOCK_LABELS[3]],
    archivedAt: null,
    createdAt: '2025-04-15T10:00:00Z',
    updatedAt: '2025-04-15T10:00:00Z',
  },
];

export const MOCK_COMMENTS: Record<string, Comment[]> = {
  'ticket-3': [
    {
      id: 'comment-1',
      ticketId: 'ticket-3',
      user: MOCK_USERS[2],
      content: 'Reproduje el error en staging. El token de refresco no se envía correctamente.',
      createdAt: '2025-04-06T09:00:00Z',
      updatedAt: '2025-04-06T09:00:00Z',
    },
    {
      id: 'comment-2',
      ticketId: 'ticket-3',
      user: MOCK_USERS[0],
      content: 'Asignado a mí para revisión. Debería estar listo hoy.',
      createdAt: '2025-04-12T10:00:00Z',
      updatedAt: '2025-04-12T10:00:00Z',
    },
  ],
};

export const MOCK_DASHBOARD = {
  createdVsClosed: [
    { month: 'Ene', created: 5, closed: 2 },
    { month: 'Feb', created: 8, closed: 6 },
    { month: 'Mar', created: 12, closed: 9 },
    { month: 'Abr', created: 7, closed: 5 },
    { month: 'May', created: 10, closed: 3 },
  ],
  byStatus: [
    { status: 'por_hacer', count: 2 },
    { status: 'en_progreso', count: 1 },
    { status: 'review', count: 1 },
    { status: 'bloqueado', count: 1 },
    { status: 'listo', count: 1 },
  ],
};
